# Usamos la imagen específica que solicitaste
FROM node:22-bookworm-slim AS base

# Configuración de pnpm
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

WORKDIR /app

COPY package.json pnpm-lock.yaml ./

# Etapa de dependencias
FROM base AS deps
RUN pnpm install --frozen-lockfile

# Etapa de desarrollo
FROM deps AS dev
COPY . .
EXPOSE 5173
CMD ["pnpm", "run", "dev", "--host"]